<div class="header-nav">
    <div class="header content">
        <div class="header-category__list">
            <div class="header-category__item">
                <a href="#" class="header-category__link">Outdoor dining</a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Outdoor Lounges</a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Outdoor DayBeds</a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Outdoor Chairs & Tables</a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Garden Furniture </a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Outdoor umbrellas </a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Balcony </a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Outdoor Heating</a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Smokers & Grills </a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Outdoor Accessories </a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Clearance Store</a>
            </div>
            <div class="header-category__item">
                <a href="#" class="header-category__link">Stores </a>
            </div>
        </div>
    </div>
</div>