<div class="achievement">
    <?= $block->getLayout()

    ->createBlock('Magento\Cms\Block\Block')

    ->setBlockId('achievement-links')

    ->toHtml();
    ?>
</div>

<script>
   require([
      'jquery',
      'slick',
      'domReady!'
   ], function ($) {
      $(".achievement").slick({
         dots: false,
         infinite: true,
         prevArrow: false,
         nextArrow: false,
         speed: 300,
         slidesToShow: 3,
         slidesToScroll: 1
      });
   });
</script>