<div class="section-categories">
    <div class="categories-box">
        <div class="categories__list">
            <?php for($i = 1; $i < 3; $i++): ?>
                <div class="category__item">
                    <?= $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('categories-box-link-'.$i)

                    ->toHtml();
                    ?>
                </div>
            <?php endfor; ?>
        </div>
    </div>
</div>


