<div class="section-inspiration">
    <div class="section-heading">
        <p>Outdoor inspiration with our instagram</p>
    </div>
    <p class="description">Find us at @burninglog, show us your furniture with #burninglog</p>

    <div class="inspiration__content">
            <?= $block->getLayout()

            ->createBlock('Magento\Cms\Block\Block')

            ->setBlockId('inspiration-block')

            ->toHtml();
            ?>
        </div>
        
        <!-- <a href="#">View our instagram</a> -->
        
    </div>
</div>

<script>

    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".inspiration__content").slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 1,
                slidesToScroll: 1
            });
        });
    });
</script>