<div class="section-new-arrivals">
    <div class="section-heading">
        <p>New Arrials</p>
    </div>

    <div class="products-arrials__list">
        <?= $block->getLayout()

        ->createBlock('Magento\Cms\Block\Block')

        ->setBlockId('products-list-block')

        ->toHtml();
        ?>
    </div>
</div>

<script>

    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".Arrials").slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 768,
                        settings: {
                            arrows: false,
                            centerMode: true,
                            centerPadding: '40px',
                            slidesToShow: 1
                        }
                    }
                ]
            });
        });
    });
</script>