<div class="showroom">
    <div class="showroom-item outdoor_elegance">
        <a href="#">
            <?= $block->getLayout()

                ->createBlock('Magento\Cms\Block\Block')

                ->setBlockId('showroom_left')

                ->toHtml(); 
            ?>
        </a>
    </div>

    <div class="showroom-item canberra_showroom">
        <button type="button" class="btn btn_showroom">Canberra Showroom</button>
        <div class="showroom_content">
        <?= $block->getLayout()

        ->createBlock('Magento\Cms\Block\Block')

        ->setBlockId('showroom_info')

        ->toHtml(); 
        ?>
        </div>
        <a href="#" class="link">View more info</a>
    </div>

    <div class="showroom-item weber">
        <a href="#">
        <?= $block->getLayout()

                ->createBlock('Magento\Cms\Block\Block')

                ->setBlockId('showroom_right')

                ->toHtml(); 
        ?>
        </a>
    </div>
</div>